In [1]:
#!/usr/bin/env python


In [2]:
import pandas as pd
# print(pd.__version__)
import numpy as np

# make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
keras = tf.keras

from tensorflow.keras.models import Model

In [3]:
lidar_data = pd.read_csv(
    "C:/Users/kcvan/MakeAIWork/KEVINPROJECT1/CSVfiles/04_L_300922 - 04_L_300922.csv",
    names=["Lidar1", "Lidar2", "Lidar3", "Lidar4", "Lidar5", "Lidar6", "Lidar7", "Lidar8", "Lidar9", "Lidar10",
           "Lidar11", "Lidar12", "Lidar13", "Lidar14", "Lidar15", "Lidar16", "SteeringAngle"])

lidar_data.head()  

Lidar1  Lidar2  Lidar3   Lidar4   Lidar5   Lidar6  Lidar7  Lidar8   Lidar9  \
0  7.4738  6.8804  8.4187  10.2916  12.9601   9.7649  5.7678  5.8949   3.9631   
1  7.4734  6.8800  8.4183  10.2912  12.9597   9.7646  5.7675  5.8946   3.9629   
2  7.4734  6.8800  8.4183  10.2912  12.9597   9.7646  5.7675  5.8946   3.9629   
3  7.4700  6.8767  8.4153  10.2884  12.9573  11.2625  5.7657  5.8933  20.0000   
4  7.4670  6.8739  8.4128  10.2860  12.9552  11.2607  5.7641  5.8923  20.0000   

   Lidar10  Lidar11  Lidar12  Lidar13  Lidar14  Lidar15  Lidar16  \
0  20.0000   5.2666   2.7754   4.3291   5.5480   1.4787   6.4672   
1  20.0000   5.2664   2.7751   4.3287   5.5477   1.4783   6.4667   
2  20.0000   5.2664   2.7751   4.3287   5.5477   1.4783   6.4667   
3  20.0000   5.2634   2.7719   4.3254   5.5442   1.4747   6.4631   
4   1.2853   5.2609   2.7692   4.3226   5.5412   4.8172   1.4716   

   SteeringAngle  
0          -32.0  
1          -32.0  
2          -32.0  
3          -31.5  
4          -39.0

In [4]:
# print(lidar_data)

In [5]:
lidar_sensors = lidar_data.copy()
lidar_angle = lidar_sensors.pop('SteeringAngle')
lidar_sensors.head()

Lidar1  Lidar2  Lidar3   Lidar4   Lidar5   Lidar6  Lidar7  Lidar8   Lidar9  \
0  7.4738  6.8804  8.4187  10.2916  12.9601   9.7649  5.7678  5.8949   3.9631   
1  7.4734  6.8800  8.4183  10.2912  12.9597   9.7646  5.7675  5.8946   3.9629   
2  7.4734  6.8800  8.4183  10.2912  12.9597   9.7646  5.7675  5.8946   3.9629   
3  7.4700  6.8767  8.4153  10.2884  12.9573  11.2625  5.7657  5.8933  20.0000   
4  7.4670  6.8739  8.4128  10.2860  12.9552  11.2607  5.7641  5.8923  20.0000   

   Lidar10  Lidar11  Lidar12  Lidar13  Lidar14  Lidar15  Lidar16  
0  20.0000   5.2666   2.7754   4.3291   5.5480   1.4787   6.4672  
1  20.0000   5.2664   2.7751   4.3287   5.5477   1.4783   6.4667  
2  20.0000   5.2664   2.7751   4.3287   5.5477   1.4783   6.4667  
3  20.0000   5.2634   2.7719   4.3254   5.5442   1.4747   6.4631  
4   1.2853   5.2609   2.7692   4.3226   5.5412   4.8172   1.4716

In [6]:
#print(lidar_sensors)

In [7]:
#lidar_angle.head()

In [8]:
lidar_sensors = np.array(lidar_sensors)
lidar_sensors

array([[ 7.474,  6.88 ,  8.419, ...,  5.548,  1.479,  6.467],
       [ 7.473,  6.88 ,  8.418, ...,  5.548,  1.478,  6.467],
       [ 7.473,  6.88 ,  8.418, ...,  5.548,  1.478,  6.467],
       ...,
       [ 1.959,  3.503,  4.726, ..., 20.   ,  2.622, 20.   ],
       [ 1.959,  3.503,  4.726, ..., 20.   ,  2.622, 20.   ],
       [ 1.959,  3.503,  4.726, ..., 20.   ,  2.622, 20.   ]])

In [9]:
normalize = keras.layers.Normalization()
normalize.adapt(lidar_sensors)

In [10]:
norm_lidar_model_01 = tf.keras.Sequential([
    normalize,
    keras.Input(shape=(16, )),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(128, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(64, activation='relu'),
    keras.layers.Dense(1)
])

norm_lidar_model_01.compile(
    loss = tf.keras.losses.MeanSquaredError(), 
    metrics = ['accuracy'],
    optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)
)


In [11]:
norm_lidar_model_01.fit(lidar_sensors, lidar_angle, epochs=500)

Epoch 1/500
363/363 [==============================] - 1s 2ms/step - loss: 92.8964 - accuracy: 0.0513
Epoch 2/500
363/363 [==============================] - 1s 1ms/step - loss: 70.6684 - accuracy: 0.0524
Epoch 3/500
363/363 [==============================] - 1s 1ms/step - loss: 60.1057 - accuracy: 0.0525
Epoch 4/500
363/363 [==============================] - 1s 1ms/step - loss: 50.6561 - accuracy: 0.0522
Epoch 5/500
363/363 [==============================] - 1s 1ms/step - loss: 42.6026 - accuracy: 0.0518
Epoch 6/500
363/363 [==============================] - 1s 1ms/step - loss: 38.7430 - accuracy: 0.0533
Epoch 7/500
363/363 [==============================] - 1s 1ms/step - loss: 34.2285 - accuracy: 0.0517
Epoch 8/500
363/363 [==============================] - 1s 1ms/step - loss: 30.2040 - accuracy: 0.0517
Epoch 9/500
363/363 [==============================] - 1s 1ms/step - loss: 27.8702 - accuracy: 0.0521
Epoch 10/500
363/363 [==============================] - 1s 1ms/step - loss: 25.334

In [12]:
val_lidar_data = pd.read_csv(
    "C:/Users/kcvan/MakeAIWork/KEVINPROJECT1/CSVfiles/validation_lidar_01.csv",
    names=["Lidar1", "Lidar2", "Lidar3", "Lidar4", "Lidar5", "Lidar6", "Lidar7", "Lidar8", "Lidar9", "Lidar10",
           "Lidar11", "Lidar12", "Lidar13", "Lidar14", "Lidar15", "Lidar16", "SteeringAngle"])

val_lidar_sensors = val_lidar_data.copy()
val_lidar_angle = val_lidar_sensors.pop('SteeringAngle')

val_lidar_sensors = np.array(val_lidar_sensors)
val_lidar_sensors

array([[ 7.377,  6.784,  8.326, ...,  5.466,  1.388,  6.373],
       [ 7.377,  6.784,  8.326, ...,  5.466,  1.388,  6.373],
       [ 7.376,  6.784,  8.326, ...,  5.465,  1.387,  6.373],
       ...,
       [20.   ,  3.115, 20.   , ..., 20.   ,  1.35 , 20.   ],
       [20.   ,  3.115, 20.   , ..., 20.   ,  1.35 , 20.   ],
       [20.   ,  3.115, 20.   , ..., 20.   ,  1.35 , 20.   ]])

In [13]:
norm_lidar_model_01.evaluate(val_lidar_sensors,  val_lidar_angle, verbose=2)

53/53 - 0s - loss: 11.4324 - accuracy: 0.0611 - 185ms/epoch - 3ms/step


[11.432358741760254, 0.061114441603422165]

In [14]:
norm_lidar_model_01.predict(val_lidar_sensors)

array([[-31.393],
       [-31.391],
       [-31.395],
       ...,
       [  2.148],
       [  2.148],
       [  2.148]], dtype=float32)

In [15]:
#norm_lidar_model_01.save('norm_lidar_model_01')

INFO:tensorflow:Assets written to: norm_lidar_model_01\assets
