In [242]:
#!/usr/bin/env python


In [243]:
import pandas as pd
# print(pd.__version__)
import numpy as np

# make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
keras = tf.keras

from tensorflow.keras.models import Model
from tensorflow import keras
from tensorflow.keras import layers

In [244]:
sonar_data = pd.read_csv(
    "C:/Users/kcvan/MakeAIWork/KEVINPROJECT1/CSVfiles/01_S_280922 - 01_S_280922.csv",
    names=["Sonar1", "Sonar2", "Sonar3", "SteeringAngle"])

#sonar_data.head()  

In [245]:
# print(sonar_data)

In [246]:
sonar_sensors = sonar_data.copy()
sonar_angle = sonar_sensors.pop('SteeringAngle')
#sonar_sensors.head()

In [247]:
#print(sonar_angle)

In [248]:
#sonar_angle.head()

In [249]:
sonar_sensors = np.array(sonar_sensors)
sonar_sensors

array([[1.451, 1.271, 1.766],
       [1.452, 1.272, 1.767],
       [1.451, 1.27 , 1.766],
       ...,
       [1.983, 1.74 , 1.353],
       [1.983, 1.74 , 1.353],
       [1.983, 1.74 , 1.353]])

In [250]:
normalize = keras.layers.Normalization()
normalize.adapt(sonar_sensors)

In [251]:
norm_sonar_model_01 = tf.keras.Sequential([
    normalize,
    keras.Input(shape=(3,)),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(32, activation='relu'),
    keras.layers.Dense(16, activation='relu'),
    keras.layers.Dense(1)
])

norm_sonar_model_01.compile(loss = tf.keras.losses.MeanSquaredError(), metrics = ['accuracy'],
                      optimizer = tf.keras.optimizers.Adam(learning_rate=0.01))

In [252]:
norm_sonar_model_01.fit(sonar_sensors, sonar_angle, epochs=200)

Epoch 1/200
157/157 [==============================] - 1s 1ms/step - loss: 47.8708 - accuracy: 0.4537
Epoch 2/200
157/157 [==============================] - 0s 1ms/step - loss: 10.5635 - accuracy: 0.5868
Epoch 3/200
157/157 [==============================] - 0s 1ms/step - loss: 6.2059 - accuracy: 0.6729
Epoch 4/200
157/157 [==============================] - 0s 1ms/step - loss: 5.8902 - accuracy: 0.7123
Epoch 5/200
157/157 [==============================] - 0s 1ms/step - loss: 4.0758 - accuracy: 0.7391
Epoch 6/200
157/157 [==============================] - 0s 1ms/step - loss: 4.6430 - accuracy: 0.7471
Epoch 7/200
157/157 [==============================] - 0s 1ms/step - loss: 3.9787 - accuracy: 0.7516
Epoch 8/200
157/157 [==============================] - 0s 1ms/step - loss: 2.9285 - accuracy: 0.7606
Epoch 9/200
157/157 [==============================] - 0s 1ms/step - loss: 3.3974 - accuracy: 0.7588
Epoch 10/200
157/157 [==============================] - 0s 1ms/step - loss: 2.6922 - accu

In [253]:
val_sonar_data = pd.read_csv(
    "C:/Users/kcvan/MakeAIWork/KEVINPROJECT1/CSVfiles/validation_sonar_01.csv",
    names=["Sonar1", "Sonar2", "Sonar3", "SteeringAngle"])

val_sonar_sensors = val_sonar_data.copy()
val_sonar_angle = val_sonar_sensors.pop('SteeringAngle')

val_sonar_sensors = np.array(val_sonar_sensors)
val_sonar_sensors

array([[1.458, 1.277, 1.77 ],
       [1.458, 1.277, 1.77 ],
       [1.458, 1.277, 1.77 ],
       ...,
       [1.782, 1.706, 1.16 ],
       [1.782, 1.706, 1.16 ],
       [1.782, 1.706, 1.16 ]])

In [254]:
norm_sonar_model_01.evaluate(val_sonar_sensors,  val_sonar_angle, verbose=2)

35/35 - 0s - loss: 0.6754 - accuracy: 0.7732 - 126ms/epoch - 4ms/step


[0.6753836870193481, 0.7731863856315613]

In [255]:
norm_sonar_model_01.predict(val_sonar_sensors)

array([[-22.341],
       [-22.346],
       [-22.346],
       ...,
       [ -0.007],
       [ -0.007],
       [ -0.007]], dtype=float32)

In [257]:
#norm_sonar_model_01.save('norm_sonar_model_01')

INFO:tensorflow:Assets written to: norm_sonar_model_01\assets
